import { fileURLToPath } from 'node:url';
import react from '@vitejs/plugin-react';
import { defineConfig } from 'vite';
import { VitePWA } from 'vite-plugin-pwa';

// SPA build. Dev server proxies /api → the local API (ops.md §3).
// @macronome/shared is aliased to source so dev needs no prebuild.

/** One taskbar-shortcut icon entry (B-259); the PNGs are generated by `gen:pwa-assets`. */
const shortcutIcon = (name: string) => ({
  src: `shortcuts/shortcut-${name}.png`,
  sizes: '96x96',
  type: 'image/png',
});
export default defineConfig({
  plugins: [
    react(),
    // Installable PWA (PWA-1, ADR-0003). App-shell precache only — `navigateFallbackDenylist`
    // keeps /api out of the SW (mirrors serveSpa); there is NO runtime caching of data.
    // registerType 'prompt' = a new build installs in the background and activates on the next
    // launch (no in-session reload); we register manually (lib/pwa/registerSw.ts) and the
    // Paramètres button forces immediate activation. Icons are committed (gen:icons).
    VitePWA({
      registerType: 'prompt',
      injectRegister: null,
      includeAssets: ['favicon.svg', 'favicon.ico', 'apple-touch-icon-180x180.png'],
      workbox: {
        navigateFallbackDenylist: [/^\/api\//],
        cleanupOutdatedCaches: true,
        // B-259: the install-dialog screenshots are seen ONCE, at install time. Precaching them
        // would put ~144KB into every visitor's cache for an image they will never see again.
        globIgnores: ['**/screenshots/**'],
      },
      manifest: {
        // B-259: `id` freezes the installed identity. Without it the browser keys the install on
        // `start_url`, so any future change there would register as a DIFFERENT app — a second
        // icon, and the existing install orphaned. Set now, while `start_url` is still '/'.
        id: '/',
        name: 'Macronome',
        short_name: 'Macronome',
        description: 'Suivi nutrition & poids',
        categories: ['health', 'fitness', 'lifestyle'],
        lang: 'fr',
        theme_color: '#0d0f12',
        background_color: '#0d0f12',
        display: 'standalone',
        // WCO (B-200, design/components/pwa.md): in the installed window, drop the OS title bar and
        // lift the app header into the freed title-bar strip (only the native window buttons remain).
        // Falls back to `display: standalone` where WCO is unsupported (older browsers) and on mobile.
        display_override: ['window-controls-overlay', 'standalone'],
        start_url: '/',
        // Single window: launching the installed app focuses the existing window (B-183).
        launch_handler: { client_mode: 'focus-existing' },
        // Taskbar right-click / icon long-press entries (B-183, design/components/pwa.md).
        // `?action=add` opens Poids with the add-weigh-in sheet (consumed once by WeightPage).
        // Per-shortcut icons (B-259): without them Windows draws the app icon five times over,
        // so the jump list is unreadable. Four glyphs are the mobile bottom nav's own (a guard
        // test enforces the parity); Paramètres has no counterpart there and is the one drawn
        // for this set. Generated by `gen:pwa-assets`, committed under public/shortcuts.
        shortcuts: [
          { name: 'Repas du jour', url: '/', icons: [shortcutIcon('meals')] },
          { name: 'Ajouter une pesée', url: '/weight?action=add', icons: [shortcutIcon('weight')] },
          { name: 'Journal', url: '/history', icons: [shortcutIcon('journal')] },
          { name: 'Stats', url: '/stats', icons: [shortcutIcon('stats')] },
          { name: 'Paramètres', url: '/settings', icons: [shortcutIcon('settings')] },
        ],
        // Shown by Edge/Chromium in the install dialog. Downscaled + WebP re-encodes of the three
        // README previews (docs/img), so nothing new is exposed and the app image grows ~144KB.
        screenshots: [
          {
            src: 'screenshots/preview.webp',
            sizes: '1280x581',
            type: 'image/webp',
            form_factor: 'wide',
          },
          {
            src: 'screenshots/preview_pc.webp',
            sizes: '1280x677',
            type: 'image/webp',
            form_factor: 'wide',
          },
          {
            src: 'screenshots/preview_mobile.webp',
            sizes: '1008x2041',
            type: 'image/webp',
            form_factor: 'narrow',
          },
        ],
        icons: [
          { src: 'pwa-64x64.png', sizes: '64x64', type: 'image/png' },
          { src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png' },
          { src: 'pwa-512x512.png', sizes: '512x512', type: 'image/png' },
          {
            src: 'maskable-icon-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
    }),
  ],
  resolve: {
    alias: {
      '@macronome/shared': fileURLToPath(new URL('../shared/src/index.ts', import.meta.url)),
    },
  },
  // B-286: bake the version of THIS bundle into the client. /api/v1/health reports the server's
  // version, so right after a deploy the card claimed to be up to date while the browser still
  // ran the old shell. Fed by the same APP_VERSION build-arg the API image receives (ADR-0002);
  // 'dev' everywhere else. Display-only and non-authoritative — the git tag stays the source
  // of truth. Read it through lib/build-version.ts, never this global directly.
  define: {
    __APP_VERSION__: JSON.stringify(process.env.APP_VERSION ?? 'dev'),
  },
  server: {
    // Bind on all IPv4 interfaces (loopback + LAN), IPv4-only — we do NOT bind ::1.
    // Why: `localhost` resolves to both 127.0.0.1 AND ::1; binding ::1 only (Vite's
    // default) wasted ~2s per new connection (Happy Eyeballs racing the dead IPv4).
    // IPv4-only means every live address is unique → no stall, and the server is now
    // reachable from the local network (mobile testing). RULE: enter via
    // http://127.0.0.1:5173 (dev machine) or http://<LAN-IP>:5173 (phone) — NEVER via
    // `localhost`, which would still race on the dead ::1.
    host: '0.0.0.0',
    port: 5173,
    proxy: {
      '/api': { target: 'http://127.0.0.1:3000', changeOrigin: true },
    },
  },
  build: {
    outDir: 'dist',
  },
});
